data:
  data_path: ./BoolQ
  train_data: train.jsonl
  dev_data: dev.jsonl
  test_data: test.jsonl
  calc_file: ./data/calc.txt
  vocab_file: ./data/vocab.pickle

preprocess:
  vocab_size: 2500
  pa_max_sent_len: 256
  qu_max_sent_len: 24

model: 
  embedding_dim: 200
  hidden_size: 200


train:
  output_dir: ./result
  output_filename_prefix: lstm
  logging_step: 200
  batch_size: 12
  epochs: 10
  lr: 0.00003
  weight_decay: 0.01
  b: 0.3

dev:
  batch_size: 8