data:
  data_path: /home/mingshuo/Dataset/BoolQ
  train_data: train.jsonl
  dev_data: dev.jsonl
  test_data: test.jsonl
  calc_file: ./data/calc.txt
  vocab_file: ./data/vocab.pickle

preprocess:
  vocab_size: 2500
  pa_max_sent_len: 256
  qu_max_sent_len: 24

model: 
  embedding_dim: 200
  hidden_size: 200


train:
  output_dir: ./result
  output_filename_prefix: lstm
  logging_step: 1000
  batch_size: 32
  epochs: 50
  lr: 0.0005
  weight_decay: 0.001
  b: 0.3

dev:
  batch_size: 8

eval:
  ckpt_path: ./result/lstm_epoch=1